#   Refer for explanation to following link:
#   https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md
[pre-push.commands.lint]
run = "pnpm lint"
stage_fixed=true

[pre-push.commands.type-check]
run = "pnpm vue-tsc"

[[pre-commit.only]]
ref = "main"

[[pre-commit.only]]
ref = "canary"

[pre-commit.commands.protected]
run = "echo 'Protected branch' && exit 1"
