import {
  help,
  notification,
  moonFill,
  arrowLeft,
  chevronUp,
  dark,
  exitBig,
  exitSmall,
  exit,
  leftBigSmall,
  leftBig,
  light,
  notificationYes,
  plusSmall,
  plus,
  profileIcon,
  profile,
  rightBig,
  rightSmall,
  settings,
  settingsDark,
  searchNormal,
  search,
  filter,
  bgNotContent,
  document,
  baseDetail
} from './icons.ts';

const Icons = {
  help: help,
  notification: notification,
  moonFill: moonFill,
  chevronDown: arrowLeft,
  chevronUp: chevronUp,
  dark: dark,
  exitBig: exitBig,
  exitSmall: exitSmall,
  exit: exit,
  leftBigSmall: leftBigSmall,
  leftBig: leftBig,
  light: light,
  notificationYes: notificationYes,
  plusSmall: plusSmall,
  plus: plus,
  profileIcon: profileIcon,
  profile: profile,
  rightBig: rightBig,
  rightSmall: rightSmall,
  settings: settings,
  settingsDark: settingsDark,
  searchNormal: searchNormal,
  search: search,
  filter: filter,
  bgNotContent: bgNotContent,
  document: document,
  baseDetail: baseDetail
};

export default Icons;
