import { App } from 'vue';
import { default as Badges } from './Badges/Badges.vue';
import { default as BreadCrumbs } from './BreadCrumbs/BreadCrumbs.vue';
import { default as Button } from './Button/Button.vue';
import { default as Switch } from './Switch/Switch.vue';
import { default as Dropdown } from './Select/Dropdown.vue';
import { default as Calendar } from './Calendar/Calendar.vue';
import { default as Dialog } from './Dialog/Dialog.vue';
import { default as Accordion } from './Accordion/Accordion.vue';
import { default as DragAndDrop } from './DragAndDrop/DragAndDrop.vue';
import { default as Card } from './Card/Card.vue';
import { default as Filter } from './Filter/Filter.vue';
import { default as Combobox } from './Select/Combobox.vue';
import { default as SelectList } from './Select/SelectList.vue';
import { default as Icon } from './Icon/Icon.vue';
import { default as Input } from './Input/Input.vue';
import { default as InputNumber } from './InputNumber/InputNumber.vue';
import { default as Search } from './Search/Search.vue';
import { default as Slider } from './Slider/Slider.vue';
import { default as Toggle } from './Toggle/Toggle.vue';
import { default as Scroll } from './Scrollbar/Scrollbar.vue';
import { default as Modal } from './Modal/ModalAnimated.vue';
import { default as Checkbox } from './Checkbox/Checkbox.vue';
import { default as UserMenu } from './UserMenu/UserMenu.vue';
import { default as Textarea } from './Textarea/Textarea.vue';
import { default as Picture } from './Picture/Picture.vue';
import { default as PushNotification } from './Notification/Notification.vue';
import { default as CopyIcon } from './CopyIcon/CopyIcon.vue';
import { default as Loader } from './Loader/Loader.vue';
import { default as FilterTag } from './FilterTag/FilterTag.vue';
import { default as CircularProgress } from './CircularProgress/CircularProgress.vue';
import { default as Popover } from './Popover/Popover.vue';
import { default as Table } from './Table/Table.vue';
import { default as TableRow } from './Table/TableRow.vue';
import { default as TableTd } from './Table/TableTd.vue';
import { default as TableTh } from './Table/TableTh.vue';
import { default as SectionTableRow } from './Table/SectionTableRow.vue';
import { default as HeadTableRow } from './Table/HeadTableRow.vue';
import { default as ScrollWrapper } from './ScrollWrapper/ScrollWrapper.vue';
import { default as Radio } from './Radio/Radio.vue';
import { default as Tooltip } from './Tooltip/Tooltip.vue';
import { default as BaseFilter } from './Select/BaseFilter.vue';
import { default as Range } from './Range/Range.vue';
import { default as TableNew } from './Table/TableNew.vue';
import { default as TableRowNew } from './Table/TableRowNew.vue';
import { default as HeadTableRowNew } from './Table/HeadTableRowNew.vue';
import { default as TableSimple } from './Table/TableSimple.vue';
import { default as Avatar } from './Avatar/Avatar.vue';
import { default as Tabs } from './Tabs/Tabs.vue';
import { default as ContentEditor } from './ContentEditor/ContentEditor.vue';
import { default as ModalCroppedAvatar } from './Cropper/ModalCroppedAvatar.vue';
import { default as TimePicker } from './TimePicker/TimePicker.vue';
import { default as vuePluginRemoveTestid } from '../helpers/vue-plugin-remove-testid';
import { getFirstTime, getLastTime } from './Calendar/date-utils';
import { IRangeForDatePicker } from './Calendar/interfaces/interfaces';
import { OptionsObject } from './Select/interface/interface';
import { IDialogProps } from './Modal/interface/interface';
import { IDataTestIdProp } from '../common/dataTestidProps';
import { IconNameEnum } from './Icon/enum/enum';
import { SizesEnum } from '../common/sizes';
import { ButtonTypeEnum } from './Button/enum/enum';
import { ColorsEnum } from '../common/colors';
import { BadgesTypeEnum } from './Badges/enum/enum';
import { ImageExtensionsEnum, VideoExtensionsEnum } from '../common/extentions';
import { InputTypeEnum, TextFieldEnum } from './Input/enum/enum';
import { TextareaTypeEnum } from './Textarea/enum';
import { CheckboxSizeEnum } from './Checkbox/enum/enum';
import { MenuTypeEnum } from './UserMenu/enum/enum';
import { default as SliderModal } from './Slider/SliderModal.vue';

declare const _default: {
    install: (app: App) => void;
};
export default _default;
export { Accordion, Badges, BreadCrumbs, Button, Dialog, Card, Calendar, DragAndDrop, Switch, SelectList, Dropdown, Textarea, Filter, Icon, Input, Combobox, InputNumber, Search, PushNotification, Picture, Scroll, Modal, Slider, Checkbox, Toggle, UserMenu, CopyIcon, Loader, FilterTag, CircularProgress, Popover, Table, TableSimple, TableNew, TableRow, TableRowNew, TableTd, TableTh, SectionTableRow, HeadTableRow, HeadTableRowNew, ScrollWrapper, Radio, Tooltip, BaseFilter, Range, Avatar, Tabs, ContentEditor, ModalCroppedAvatar, TimePicker, type IDialogProps, type IRangeForDatePicker, type OptionsObject, type IDataTestIdProp, CheckboxSizeEnum, TextFieldEnum, IconNameEnum, SizesEnum, ButtonTypeEnum, ColorsEnum, ImageExtensionsEnum, BadgesTypeEnum, VideoExtensionsEnum, InputTypeEnum, TextareaTypeEnum, MenuTypeEnum, getLastTime, getFirstTime, vuePluginRemoveTestid, SliderModal };
