name: Deploy Storybook to Vercel

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build Storybook
        run: pnpm run build-storybook

      - name: Install Vercel CLI
        run: pnpm add -g vercel

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          set -e
          if [ -z "${VERCEL_TOKEN}" ]; then
            echo "VERCEL_TOKEN is not set. Create a Vercel Personal Token and add it as a repository secret named VERCEL_TOKEN."
            exit 1
          fi

          # Deploy the static site directory
          vercel --token "$VERCEL_TOKEN" --prod --confirm ./storybook-static || vercel --token "$VERCEL_TOKEN" --prod --confirm ./storybook-static
