name: Build and pusblish npm package
on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Linting project
        run: pnpm run lint
      - uses: actions/upload-artifact@v4
        with:
          name: project
          path: .

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - uses: actions/download-artifact@v4
        with:
          name: project
          path: .
      - name: Build project
        run: pnpm run build
      - uses: actions/upload-artifact@v4
        with:
          name: published-to-npm-folder
          path: ./dist
  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: published-to-npm-folder
          path: .
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: update-package-json
          path: |
            package.json
            package-lock.json

  update-package-json:
    runs-on: ubuntu-latest
    needs: publish
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: update-package-json
          path: .
      - uses: stefanzweifel/git-auto-commit-action@v5
