name: Build and Commit PR
on:
  workflow_dispatch:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Linting project
        run: pnpm run lint

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build project
        run: pnpm run build
      - name: Copy package and README
        run: |
          mkdir -p npm-package
          cp -r package.json npm-package/package.json
          cp -r README.md npm-package/README.md
          cp -r dist npm-package/dist
      - uses: actions/upload-artifact@v4
        with:
          name: published-to-npm-folder
          path: ./npm-package
  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: published-to-npm-folder
          path: .
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: 'rls'
